package com.eventos.pf.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SesionCompraAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSesionCompraAllPropertiesEquals(SesionCompra expected, SesionCompra actual) {
        assertSesionCompraAutoGeneratedPropertiesEquals(expected, actual);
        assertSesionCompraAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSesionCompraAllUpdatablePropertiesEquals(SesionCompra expected, SesionCompra actual) {
        assertSesionCompraUpdatableFieldsEquals(expected, actual);
        assertSesionCompraUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSesionCompraAutoGeneratedPropertiesEquals(SesionCompra expected, SesionCompra actual) {
        assertThat(actual)
            .as("Verify SesionCompra auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSesionCompraUpdatableFieldsEquals(SesionCompra expected, SesionCompra actual) {
        assertThat(actual)
            .as("Verify SesionCompra relevant properties")
            .satisfies(a -> assertThat(a.getPasoActual()).as("check pasoActual").isEqualTo(expected.getPasoActual()))
            .satisfies(a ->
                assertThat(a.getAsientosSeleccionados()).as("check asientosSeleccionados").isEqualTo(expected.getAsientosSeleccionados())
            )
            .satisfies(a -> assertThat(a.getDatosPersonas()).as("check datosPersonas").isEqualTo(expected.getDatosPersonas()))
            .satisfies(a -> assertThat(a.getFechaCreacion()).as("check fechaCreacion").isEqualTo(expected.getFechaCreacion()))
            .satisfies(a -> assertThat(a.getFechaExpiracion()).as("check fechaExpiracion").isEqualTo(expected.getFechaExpiracion()))
            .satisfies(a -> assertThat(a.getActiva()).as("check activa").isEqualTo(expected.getActiva()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSesionCompraUpdatableRelationshipsEquals(SesionCompra expected, SesionCompra actual) {
        assertThat(actual)
            .as("Verify SesionCompra relationships")
            .satisfies(a -> assertThat(a.getEvento()).as("check evento").isEqualTo(expected.getEvento()));
    }
}
