package com.eventos.pf.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VentaAsientoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVentaAsientoAllPropertiesEquals(VentaAsiento expected, VentaAsiento actual) {
        assertVentaAsientoAutoGeneratedPropertiesEquals(expected, actual);
        assertVentaAsientoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVentaAsientoAllUpdatablePropertiesEquals(VentaAsiento expected, VentaAsiento actual) {
        assertVentaAsientoUpdatableFieldsEquals(expected, actual);
        assertVentaAsientoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVentaAsientoAutoGeneratedPropertiesEquals(VentaAsiento expected, VentaAsiento actual) {
        assertThat(actual)
            .as("Verify VentaAsiento auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVentaAsientoUpdatableFieldsEquals(VentaAsiento expected, VentaAsiento actual) {
        assertThat(actual)
            .as("Verify VentaAsiento relevant properties")
            .satisfies(a -> assertThat(a.getFila()).as("check fila").isEqualTo(expected.getFila()))
            .satisfies(a -> assertThat(a.getColumna()).as("check columna").isEqualTo(expected.getColumna()))
            .satisfies(a -> assertThat(a.getPersona()).as("check persona").isEqualTo(expected.getPersona()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVentaAsientoUpdatableRelationshipsEquals(VentaAsiento expected, VentaAsiento actual) {
        assertThat(actual)
            .as("Verify VentaAsiento relationships")
            .satisfies(a -> assertThat(a.getVenta()).as("check venta").isEqualTo(expected.getVenta()));
    }
}
